const actionTypes = {
  FETCH_REQUEST_POPULAR: 'FETCH_REQUEST_POPULAR',
  FETCH_SUCCESS_POPULAR: 'FETCH_SUCCESS_POPULAR',
  FETCH_ERROR_POPULAR: 'FETCH_ERROR_POPULAR',

  FETCH_REQUEST_MOVIE_BY_ID: 'FETCH_REQUEST_MOVIE_BY_ID',
  FETCH_SUCCESS_MOVIE_BY_ID: 'FETCH_SUCCESS_MOVIE_BY_ID',
  FETCH_ERROR_MOVIE_BY_ID: 'FETCH_ERROR_MOVIE_BY_ID',

  FETCH_REQUEST_GENRES: 'FETCH_REQUEST_GENRES',
  FETCH_SUCCESS_GENRES: 'FETCH_SUCCESS_GENRES',
  FETCH_ERROR_GENRES: 'FETCH_ERROR_GENRES',

  FETCH_REQUEST_SEARCH_MOVIE: 'FETCH_REQUEST_SEARCH_MOVIE',
  FETCH_SUCCESS_SEARCH_MOVIE: 'FETCH_SUCCESS_SEARCH_MOVIE',
  FETCH_ERROR_SEARCH_MOVIE: 'FETCH_ERROR_SEARCH_MOVIE',

  FETCH_REQUEST_REACOMMENDATIONS: 'FETCH_REQUEST_REACOMMENDATIONS',
  FETCH_SUCCESS_REACOMMENDATIONS: 'FETCH_SUCCESS_REACOMMENDATIONS',
  FETCH_ERROR_REACOMMENDATIONS: 'FETCH_ERROR_REACOMMENDATIONS',

  FETCH_REQUEST_ACTORS_INFO: 'FETCH_REQUEST_ACTORS_INFO',
  FETCH_SUCCESS_ACTORS_INFO: 'FETCH_SUCCESS_ACTORS_INFO',
  FETCH_ERROR_ACTORS_INFO: 'FETCH_ERROR_ACTORS_INFO',
};
export default actionTypes;
